// Rotinas Uniface Diária
const ROTINAS_DIARIA = [
  { id:'d0a', hora:'00:00', texto:'Abrir Corvu – Corvu\\Data\\Eis\\Csf_online – Geral', obs:'Transporte_hora', caminho:'Serviço Batch/Transporte/Abrir Corvu – Corvu\\Data\\Eis\\Csf_online – Geral', campos:[{k:'geral',label:'Geral'},{k:'transporte_hora',label:'Transporte_hora'}], semStatus:true, secao:'Início do dia' },
  { id:'d1', hora:'01:00', texto:'Rotina Credicoamo - Serviços Bancários\\Produção\\Rotina Diária Provisão de Risco', obs:'SBRIJ001', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Provisão de Risco', campos:[{k:'srv',label:'Servidor'},{k:'ter',label:'Terminal'}], secao:'Madrugada' },
  { id:'d2', hora:'01:00', texto:'Rotina Credicoamo - 1 - Serviços Bancários\\Produção\\Rotina Diária - Fechamento dia - Central', obs:'SBCCJ001', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária - Fechamento dia - Central', campos:[{k:'srv',label:'Servidor'},{k:'ter',label:'Terminal'}], secao:'Madrugada' },
  { id:'d3', hora:'01:00', texto:'Rotina Credicoamo - 2 - Serviços Bancários\\Produção\\Rotina Diária – Aplicações - Adm Central', obs:'SBAPJ002', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária – Aplicações - Adm Central', campos:[{k:'srv',label:'Servidor'},{k:'ter',label:'Terminal'}], secao:'Madrugada' },
  { id:'d4', hora:'01:00', texto:'Rotina Credicoamo - 2 - Serviços Bancários\\Produção\\Rotina Diária Aplicações - Produção', obs:'SBAPJ001', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Aplicações - Produção', campos:[{k:'srv',label:'Servidor'},{k:'ter',label:'Terminal'}], secao:'Madrugada' },
  { id:'d5', hora:'01:00', texto:'Rotina Credicoamo - 2 - Serviços Bancários\\Produção\\Rotina Diária Contabilidade – Produção', obs:'ACTBJ001 - executar junto com SBAPJ001 e SBAPJ002 após SBCCJ001', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Contabilidade – Produção', campos:[{k:'srv',label:'Servidor'},{k:'ter',label:'Terminal'}], secao:'Madrugada' },
  { id:'d6', hora:'04:00', texto:'Integração de Crachá Motorista (Ronda/Cielo)', obs:'RH', caminho:'Serviço Batch/Recursos Humanos/Integração de Crachá Motorista (Ronda/Cielo)', secao:'Madrugada' },
  { id:'d7', hora:'05:00', texto:'Bloqueio Cliente Base CISP', obs:'Financeiro/Análise de Crédito', caminho:'Serviço Batch/Financeiro/Análise de Crédito/Bloqueio Cliente Base CISP', secao:'Madrugada' },
  { id:'d8', hora:'05:30', texto:'Rotina Sincronização Realizado Diária', obs:'Cooperados – Executar após BI DM', caminho:'Serviço Batch/Cooperados/Rotina Sincronização Realizado Diária', secao:'Madrugada' },
  { id:'d9a', hora:'06:00', texto:'Job-APSs Diário - Moinho e Gordurosos', obs:'Industrial', caminho:'Serviço Batch/Industrial/Job-APSs Diário - Moinho e Gordurosos', secao:'Manhã' },
  { id:'d9b', hora:'06:00', texto:'Job-APSs Diário - Ração', obs:'Industrial', caminho:'Serviço Batch/Industrial/Job-APSs Diário - Ração', secao:'Manhã' },
  { id:'d10', hora:'06:30', texto:'Exportação Planejamento Semente', obs:'Sementes', caminho:'Serviço Batch/Sementes/Exportação Planejamento Semente', secao:'Manhã' },
  { id:'d11', hora:'06:30', texto:'Rotina Diária RH (manhã)', obs:'Recursos Humanos', caminho:'Serviço Batch/Recursos Humanos/Rotina Diária RH (manhã)', secao:'Manhã' },
  { id:'d12', hora:'06:30', texto:'Rotina Diária Cotação Online', obs:'Fornecedores – Executar após BI DM', caminho:'Serviço Batch/Fornecedores/Rotina Diária Cotação Online', secao:'Manhã' },
  { id:'d13', hora:'', texto:'Arquivo de Retorno - Listar Bco Retorno Especial (F: Sistemas/ContasReceber/IntegraBanco)', obs:'Financeiro/Contas a Receber - Após receber arquivos dos bancos', caminho:'Serviço Batch/Financeiro/Contas a Receber/Arquivo de Retorno - Listar Bco Retorno Especial', secao:'Manhã' },
  { id:'d14', hora:'', texto:'Arquivo de Retorno - Desbloquear Pedidos Fatpem', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Arquivo de Retorno - Desbloquear Pedidos Fatpem', secao:'Manhã' },
  { id:'d15', hora:'', texto:'Geração Arquivo Corvu', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Geração Arquivo Corvu', secao:'Manhã' },
  { id:'d16', hora:'', texto:'Diário - Bloqueio Contas a Receber', obs:'Fatpem - Não executar no sábado', caminho:'Serviço Batch/Fatpem/Diário - Bloqueio Contas a Receber', secao:'Manhã' },
  { id:'d18', hora:'07:00', texto:'Rotina Sincronização Download Pedidos Neogrid', obs:'Cooperados - 47-3043-7600 opção 1', caminho:'Serviço Batch/Cooperados/Rotina Sincronização Download Pedidos Neogrid', secao:'Manhã' },
  { id:'d19', hora:'07:00', texto:'Job Pgto Diário Automático', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Pgto Diário Automático', secao:'Manhã' },
  { id:'d20a', hora:'07:00', texto:'BradescoSeguros – proposta Auto/cancelados', obs:'Credicoamo Seguros', caminho:'Serviço Batch/Credicoamo Seguros/BradescoSeguros – proposta Auto/cancelados', campos:[{k:'arquivo',label:'OK / Sem arquivo'}], semStatus:true, secao:'Manhã' },
  { id:'d20b', hora:'07:00', texto:'Importação Arquivos Seguradoras', obs:'Credicoamo Seguros', caminho:'Serviço Batch/Credicoamo Seguros/Importação Arquivos Seguradoras', secao:'Manhã' },
  { id:'d21', hora:'07:15', texto:'Rotina Diária TV', obs:'Cooperados - Iniciar Rotina', caminho:'Serviço Batch/Cooperados/Rotina Diária TV', secao:'Manhã' },
  { id:'d22', hora:'08:00', texto:'Job Diário Transporte', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Diário Transporte', secao:'Manhã' },
  { id:'d23', hora:'08:00', texto:'Conferência do Processo Contábil (Administrativo/Contabilidade)', obs:'Administrativo/Contabilidade', caminho:'Serviço Batch/Administrativa/Contabilidade/Conferência do Processo Contábil', secao:'Manhã' },
  { id:'d24', hora:'09:00', texto:'Rotina Assinatura Digital', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Assinatura Digital', secao:'Manhã' },
  { id:'d17', hora:'11:00', texto:'Receber arq. Cartões + Carga diária Aut. Extrato Eletrônico Cartões (Financeiro/Contas a Receber)', obs:'Financeiro/Contas a Receber - Receber arquivos de Cartões 11:00h', caminho:'Serviço Batch/Financeiro/Contas a Receber/Receber arq. Cartões + Carga diária Aut. Extrato', campo:'Cartões OK ___', semStatus:true, secao:'Meio-dia' },
  { id:'d25', hora:'11:00', texto:'Carga Diária Automática de Extrato Eletrônico de Cartões', obs:'Financeiro - Receber arquivos de Cartões 11:00h', caminho:'Serviço Batch/Financeiro/Contas a Receber/Carga Diária Automática Extrato Eletrônico Cartões', secao:'Meio-dia' },
  { id:'d26', hora:'11:00', texto:'Rotina Diária Unif. de Vendas para Extrato Eletrônico de Cartões (S.B.\\Financeiro\\Contas a Receber)', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Contas a Receber/Rotina Diária Unif. de Vendas para Extrato Eletrônico de Cartões', secao:'Meio-dia' },
  { id:'d27a', hora:'12:00', texto:'Job-APSs Diário - Moinho', obs:'Industrial', caminho:'Serviço Batch/Industrial/Job-APSs Diário - Moinho', secao:'Meio-dia' },
  { id:'d27b', hora:'12:00', texto:'Job-APSs Diário - Ração', obs:'Industrial', caminho:'Serviço Batch/Industrial/Job-APSs Diário - Ração', secao:'Meio-dia' },
  { id:'d28', hora:'12:00', texto:'Rotina Diária do RH – meio-dia', obs:'RH', caminho:'Serviço Batch/Recursos Humanos/Rotina Diária do RH – meio-dia', secao:'Meio-dia' },
  { id:'d29', hora:'12:00', texto:'Rotina Assinatura Digital', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Assinatura Digital', secao:'Meio-dia' },
  { id:'d30', hora:'12:00', texto:'Validação de Índice', obs:'Aplicações/Rotina Diária', caminho:'Serviço Batch/Aplicações/Rotina Diária/Validação de Índice', secao:'Meio-dia' },
  { id:'d31', hora:'12:00', texto:'Arquivo de Remessa', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Arquivo de Remessa', campos:[{k:'brasil',label:'Brasil'},{k:'itau',label:'Itaú'},{k:'bradesco',label:'Bradesco'}], secao:'Meio-dia' },
  { id:'d32', hora:'12:00', texto:'Envio de Email de Boletos para Clientes', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Envio de Email de Boletos para Clientes', secao:'Meio-dia' },
  { id:'d33', hora:'12:30', texto:'Exportação Planejamento Semente', obs:'Sementes', caminho:'Serviço Batch/Sementes/Exportação Planejamento Semente', secao:'Meio-dia' },
  { id:'d34', hora:'12:30', texto:'Rotina Diária – AVV e Coamo Brasil', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Rotina Diária – AVV e Coamo Brasil', secao:'Meio-dia' },
  { id:'d35a', hora:'13:00', texto:'Bradesco Seguros – Proposta Auto/Cancelados', obs:'Credicoamo Seguros', caminho:'Serviço Batch/Credicoamo Seguros/Bradesco Seguros – Proposta Auto/Cancelados', secao:'Tarde' },
  { id:'d35b', hora:'13:00', texto:'Importação Arquivos Seguradoras', obs:'Credicoamo Seguros', caminho:'Serviço Batch/Credicoamo Seguros/Importação Arquivos Seguradoras', secao:'Tarde' },
  { id:'d36', hora:'13:15', texto:'Diário – Bloqueio de Pedidos com Saldo de Embarque', obs:'Fatpem - Executa no sábado', caminho:'Serviço Batch/Fatpem/Diário – Bloqueio de Pedidos com Saldo de Embarque', secao:'Tarde' },
  { id:'d37', hora:'14:00', texto:'Rotina Diária Unif. de Recebimento para Extrato Eletrônico de Cartões (S.B.\\Financeiro\\Contas a Receber)', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Contas a Receber/Rotina Diária Unif. de Recebimento para Extrato Eletrônico de Cartões', secao:'Tarde' },
  { id:'d38', hora:'14:00', texto:'Rotina Assinatura Digital', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Assinatura Digital', secao:'Tarde' },
  { id:'d39', hora:'17:00', texto:'Diário - Cancelar Pedidos sem limite Crédito', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Diário - Cancelar Pedidos sem limite Crédito', secao:'Tarde' },
  { id:'d40', hora:'18:00', texto:'Estoque Corvu', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Estoque Corvu', secao:'Noite' },
  { id:'d41', hora:'18:00', texto:'Rotina Assinatura Digital', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Assinatura Digital', secao:'Noite' },
  { id:'d42', hora:'18:00', texto:'Arquivo de Remessa - Enviar Arquivos aos Bancos', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Arquivo de Remessa - Enviar Arquivos aos Bancos', campos:[{k:'brasil',label:'Brasil'},{k:'itau',label:'Itaú'},{k:'bradesco',label:'Bradesco'}], secao:'Noite' },
  { id:'d43', hora:'18:00', texto:'Envio de Email de Boletos para Clientes', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Envio de Email de Boletos para Clientes', secao:'Noite' },
  { id:'d44', hora:'18:00', texto:'Rotina CCF: Serviço Batch/Cooperados/Rotinas – Cadastro/Executar Rotina CCF', obs:'Cooperados/Rotinas-Cadastro', caminho:'Serviço Batch/Cooperados/Rotinas-Cadastro/Executar Rotina CCF', secao:'Noite' },
  { id:'d45', hora:'18:30', texto:'Rotina Diária - DRP', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária - DRP', secao:'Noite' },
  { id:'d46', hora:'18:30', texto:'I:\\Corvu\\Data\\Producao\\Diaria\\Diretorio_Corvu_Historico', obs:'I:\\Corvu\\Data\\Producao\\Diaria', caminho:'I:\\Corvu\\Data\\Producao\\Diaria\\Diretorio_Corvu_Historico', secao:'Noite' },
  { id:'d47', hora:'18:30', texto:'Job Semanal – Importação Base CISP', obs:'Financeiro/Análise de Crédito - Executar SEXTA', caminho:'Serviço Batch/Financeiro/Análise de Crédito/Job Semanal – Importação Base CISP', secao:'Noite' },
  { id:'d48', hora:'18:30', texto:'Credicoamo\\Logon\\Serviços Bancários\\Produção\\Rotina diária - Gera Arquivos para Coamo', obs:'Credicoamo - SbfiJ003', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina diária - Gera Arquivos para Coamo', secao:'Noite' },
  { id:'d49', hora:'18:30', texto:'Credicoamo - Serviços Bancários\\Produção\\Rotina Diária Financiamento – Produção', obs:'Credicoamo - SbfiJ001', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Financiamento – Produção', secao:'Noite' },
  { id:'d50', hora:'19:30', texto:'Credicoamo - Serviços Bancários\\Produção\\Rotina Diária Financiamento – Outros', obs:'Credicoamo - Sbfij011', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Financiamento – Outros', secao:'Noite' },
  { id:'d51', hora:'19:30', texto:'Credicoamo - Serviços Bancários\\Produção\\Rotina Diária – Risco de Crédito', obs:'Credicoamo - SbfiJ005', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária – Risco de Crédito', secao:'Noite' },
  { id:'d52', hora:'20:00', texto:'Credicoamo - Serviços Bancários\\Produção\\Rotina Diária Diversos – Produção', obs:'Credicoamo - SbfiJ006', caminho:'Credicoamo/Serviços Bancários/Produção/Rotina Diária Diversos – Produção', secao:'Noite' },
  { id:'d53', hora:'20:00', texto:'CreOP002 – Salva Diária Credicoamo', obs:'De segunda a sexta', caminho:'Serviço Batch/CreOP002 – Salva Diária Credicoamo', campo:'OK ___', semStatus:true, secao:'Noite' },
  { id:'d54', hora:'19:00', texto:'Job Diário – Sistemas Diversos', obs:'Sistema - Após BI - GSISJ002 (Sexta-feira)', caminho:'Serviço Batch/Sistema/Job Diário – Sistemas Diversos', secao:'Noite' },
  { id:'d55', hora:'19:00', texto:'Rotina Batch Diária Envio de Notificação – Gestão Reclamação de Sementes', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Batch Diária Envio de Notificação – Gestão', secao:'Noite' },
  { id:'d56', hora:'19:00', texto:'Job Cálculo do Prêmio de Produção', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Cálculo do Prêmio de Produção', secao:'Noite' },
  { id:'d57', hora:'19:00', texto:'Rotina Diária (Metas de Fornecimentos de Insumos)', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária (Metas de Fornecimentos de Insumos)', secao:'Noite' },
  { id:'d58', hora:'19:00', texto:'Emissão de Relatórios Batch', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Emissão de Relatórios Batch', secao:'Noite' },
  { id:'d59', hora:'19:00', texto:'Seguro Prestamista / Rotina Diária', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Seguro Prestamista / Rotina Diária', secao:'Noite' },
  { id:'d60', hora:'19:00', texto:'Preço/Corvu', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Preço/Corvu', campo:'View ___', semStatus:true, secao:'Noite' },
  { id:'d61', hora:'19:00', texto:'Contabilização Diária Seguros', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Seguros/Contabilização Diária', secao:'Noite' },
  { id:'d62', hora:'19:00', texto:'Rotina Diária Ass. Técnica Cooperado', obs:'Astec', caminho:'Serviço Batch/Astec/Rotina Diária Ass. Técnica Cooperado', secao:'Noite' },
  { id:'d63', hora:'19:00', texto:'Rotina Diária Mobilidade', obs:'Astec', caminho:'Serviço Batch/Astec/Rotina Diária Mobilidade', secao:'Noite' },
  { id:'d64', hora:'19:00', texto:'Rotina Diária Unimed (Serviço Batch/Cooperados/Rotinas Unimed) – SKYLINE', obs:'Cooperados/Rotinas Unimed - SKYLINE', caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Diária Unimed', secao:'Noite' },
  { id:'d65', hora:'19:00', texto:'Job Diário Financiamentos', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Financiamentos/Job Diário Financiamentos', secao:'Noite' },
  { id:'d66', hora:'19:00', texto:'Rotina Diária – Cobrança Judicial – Dias úteis (Serviço Batch/Administrativa/Cobrança Judicial)', obs:'Administrativa', caminho:'Serviço Batch/Administrativa/Cobrança Judicial/Rotina Diária – Dias úteis', secao:'Noite' },
  { id:'d67', hora:'19:00', texto:'Fiscal – Ressarcimento ICMS-ST', obs:'Administrativa/Fiscal', caminho:'Serviço Batch/Administrativa/Fiscal/Fiscal – Ressarcimento ICMS-ST', secao:'Noite' },
  { id:'d68', hora:'19:00', texto:'Rotina Diária RH', obs:'Recursos Humanos', caminho:'Serviço Batch/Recursos Humanos/Rotina Diária RH', secao:'Noite' },
  { id:'d69', hora:'19:00', texto:'Rotina Diária / Registro Preliminar', obs:'RH', caminho:'Serviço Batch/Recursos Humanos/Rotina Diária / Registro Preliminar', secao:'Noite' },
  { id:'d70', hora:'19:00', texto:'Rotina Diária eSocial', obs:'eSocial', caminho:'Serviço Batch/eSocial/Rotina Diária eSocial', secao:'Noite' },
  { id:'d71', hora:'19:00', texto:'Diário CIAP', obs:'Administrativo/Ciap', caminho:'Serviço Batch/Administrativo/Ciap/Diário CIAP', secao:'Noite' },
  { id:'d72', hora:'19:00', texto:'Importar Arquivo Retorno Telefonia', obs:'Administrativa/Gestão de Telefonia', caminho:'Serviço Batch/Administrativa/Gestão de Telefonia/Importar Arquivo Retorno Telefonia', secao:'Noite' },
  { id:'d73', hora:'19:00', texto:'Rotina Diária Cadastro', obs:'Cooperados - Após Rotina do CCF', caminho:'Serviço Batch/Cooperados/Rotina Diária Cadastro', campo:'Pcad ___', semStatus:true, secao:'Noite' },
  { id:'d74', hora:'19:00', texto:'Rotina Diária Auxiliar - Cadastro', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária Auxiliar - Cadastro', secao:'Noite' },
  { id:'d75', hora:'20:00', texto:'Job Diário Crédito Rural', obs:'Financeiro/Financiamento', caminho:'Serviço Batch/Financeiro/Financiamentos/Job Diário Crédito Rural', secao:'Noite' },
  { id:'d76', hora:'20:00', texto:'Job Programação Automática', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Programação Automática', secao:'Noite' },
  { id:'d77', hora:'20:00', texto:'Diária Patrimônio', obs:'Administrativa/Contabilidade', caminho:'Serviço Batch/Administrativa/Contabilidade/Diária Patrimônio', secao:'Noite' },
  { id:'d78', hora:'20:00', texto:'Job Diário – Grade (Serviço Batch/Financeiro/Grade)', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Job Diário – Grade', secao:'Noite' },
  { id:'d79', hora:'20:00', texto:'Job Diário – Caixa (Serviço Batch/Financeiro/Caixa)', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Job Diário – Caixa', secao:'Noite' },
  { id:'d80', hora:'20:00', texto:'Sincronização Download DRP Neogrid', obs:'Almoxarifado', caminho:'Serviço Batch/Almoxarifado/Sincronização Download DRP Neogrid', secao:'Noite' },
  { id:'d81', hora:'20:00', texto:'Rotina Diária Projetos Técnicos', obs:'Astec - Antes do Sipa (dias úteis e domingo)', caminho:'Serviço Batch/Astec/Rotina Diária Projetos Técnicos', secao:'Noite' },
  { id:'d82', hora:'21:00', texto:'Reiniciar Servidor BBSIA01 – Shutdown -r -f -t 5 -m \\\\BBSIA01', obs:'Shutdown -r -f -t 5 -m \\\\BBSIA01', caminho:'Reiniciar Servidor BBSIA01 – Shutdown -r -f -t 5 -m \\\\BBSIA01', secao:'Noite' },
  { id:'d83', hora:'21:00', texto:'SPTS08X – Backup ERStudio', obs:'SPTS08X', caminho:'SPTS08X – Backup ERStudio', secao:'Noite' },
  { id:'d84', hora:'21:00', texto:'Rotina Diária IBM Máximo', obs:'Fornecedores', caminho:'Serviço Batch/Fornecedores/Rotina Diária IBM Máximo', secao:'Noite' },
  { id:'d85', hora:'21:00', texto:'Rotina Diária TV - Previsão Tempo', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária TV - Previsão Tempo', secao:'Noite' },
  { id:'d86', hora:'21:00', texto:'Job Diário de Comprovação', obs:'Financeiro/Financiamentos', caminho:'Serviço Batch/Financeiro/Financiamentos/Job Diário de Comprovação', secao:'Noite' },
  { id:'d87', hora:'21:00', texto:'BradescoSeguros – Apólices Auto / Extrato Comissões / Sompo + Credicoamo\\Logon\\Serviços Bancários\\Produção\\Importar Seguros da Credi Seguros', obs:'Executar no feriado - Sbfij004', caminho:'Credicoamo/Serviços Bancários/Produção/Importar Seguros da Credi Seguros – Sbfij004', secao:'Noite' },
  { id:'d88', hora:'21:00', texto:'Carteira de Comissões Diária', obs:'Credicoamo Seguros - Após rotina diária', caminho:'Serviço Batch/Credicoamo Seguros/Carteira de Comissões Diária', secao:'Noite' },
  { id:'d89', hora:'21:00', texto:'Contabilização Diária Arcam', obs:'Arcam', caminho:'Serviço Batch/Arcam/Contabilização Diária Arcam', secao:'Noite' },
  { id:'d90', hora:'21:00', texto:'Contabilização Contas a Receber', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Contabilização Contas a Receber', secao:'Noite' },
  { id:'d91', hora:'21:00', texto:'Rotina Batch Diária Sementes', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Batch Diária Sementes', secao:'Noite' },
  { id:'d92', hora:'21:00', texto:'Job Diário - Geração de Arquivo para ECM', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Job Diário - Geração de Arquivo para ECM', secao:'Noite' },
  { id:'d93', hora:'21:00', texto:'Diário – Rotas Bloqueadas', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Diário – Rotas Bloqueadas', secao:'Noite' },
  { id:'d94', hora:'21:00', texto:'Rotina Diária Sipa', obs:'Cooperados/Rotinas Sipa - Após Rotina do Astec', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária Sipa', secao:'Noite' },
  { id:'d95', hora:'21:00', texto:'Rotina Diária Auxiliar - SIPA', obs:'Cooperados/Rotinas Sipa', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária Auxiliar - SIPA', secao:'Noite' },
  { id:'d96', hora:'21:00', texto:'Carga Matrículas', obs:'Informações Executivas - Após Rotina diária do Sipa (PATDJ001)', caminho:'Serviço Batch/Informações Executivas/Carga Matrículas', secao:'Noite' },
  { id:'d97', hora:'22:00', texto:'Rotina Diária Gestão Crédito', obs:'Credicoamo Seguros', caminho:'Serviço Batch/Credicoamo Seguros/Rotina Diária Gestão Crédito', secao:'Noite' },
  { id:'d98', hora:'22:00', texto:'Diária Fiscal', obs:'Administrativa/Fiscal', caminho:'Serviço Batch/Administrativa/Fiscal/Diária Fiscal', secao:'Noite' },
  { id:'d99', hora:'22:00', texto:'Gerar NFs Automáticas da Fixação de CN', obs:'Comercial - Antes do Job Cfatj001', caminho:'Serviço Batch/Comercial/Gerar NFs Automáticas da Fixação de CN', secao:'Noite' },
  { id:'d100', hora:'22:00', texto:'Job Diário Controle Bancário (Serviço Batch/Financeiro/Controle Bancário)', obs:'Financeiro - Após Diário Crédito Rural - Executar no feriado', caminho:'Serviço Batch/Financeiro/Controle Bancário/Job Diário', secao:'Noite' },
  { id:'d101', hora:'22:00', texto:'Rotina Diária Aplicações (Serviço Batch/Aplicações/Rotina Diária): Coamo / Credicoamo Seguros / Arcam / Fups', obs:'Após Rotina Diária Bancos', caminho:'Serviço Batch/Aplicações/Rotina Diária - Coamo / Credicoamo Seguros / Arcam / Fups', secao:'Noite' },
  { id:'d102', hora:'23:00', texto:'Assíncronos Coamo / Restore Credicoamo (domingos) – J:/Credicoamo/Central/GERTI/Analistas/Restore/', obs:'Após 23:00h', caminho:'Assíncronos Coamo / Restore Credicoamo – J:/Credicoamo/Central/GERTI/Analistas/Restore/', secao:'Noite' },
  { id:'d103', hora:'23:00', texto:'Rotina Diária Fornecedores', obs:'Fornecedores', caminho:'Serviço Batch/Fornecedores/Rotina Diária Fornecedores', secao:'Noite' },
  { id:'d104', hora:'23:00', texto:'Rotina Diária Memoriais', obs:'Administrativo/Projetos e Memoriais - Executar feriado', caminho:'Serviço Batch/Administrativa/Projetos e Memoriais/Rotina Diária Memoriais', secao:'Noite' },
  { id:'d105', hora:'23:00', texto:'Job Diário – Identif. e Notif. de Anomalias', obs:'Sistema', caminho:'Serviço Batch/Sistema/Job Diário – Identif. e Notif. de Anomalias', secao:'Noite' },
  { id:'d106', hora:'23:00', texto:'Rotina Diária Controle e Integração Defensivos', obs:'Astec', caminho:'Serviço Batch/Astec/Rotina Diária Controle e Integração Defensivos', secao:'Noite' },
  { id:'d107', hora:'23:00', texto:'Iniciar Carga TM1/Credicoamo (Serviço Batch/Administrativa/Contabilidade/TM1/Credicoamo)', obs:'Administrativa/Contabilidade', caminho:'Serviço Batch/Administrativa/Contabilidade/Iniciar Carga TM1/Credicoamo', secao:'Noite' },
  { id:'d108', hora:'23:50', texto:'Diário - Geração NF Transferência', obs:'Fatpem - Antes das 00:00h', caminho:'Serviço Batch/Fatpem/Diário - Geração NF Transferência', secao:'Noite' },

  // ── Após 00:01h ────────────────────────────────────────────────────
  { id:'d109', hora:'00:01', texto:'Geração de Duplicatas – Diário', obs:'Financeiro/Duplicatas', caminho:'Serviço Batch/Financeiro/Duplicatas/Geração de Duplicatas – Diário', secao:'Após meia-noite' },
  { id:'d110', hora:'00:01', texto:'Rotina Diária - Sistema Comercial', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Diária - Sistema Comercial', secao:'Após meia-noite' },
  { id:'d111', hora:'00:01', texto:'Rotina Diária - Sistema Comercial AVV', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Diária - Sistema Comercial AVV', secao:'Após meia-noite' },
  { id:'d112', hora:'00:01', texto:'Rotina Diária - Sist. Comercial Oper. Exportação', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Diária - Sist. Comercial Oper. Exportação', secao:'Após meia-noite' },
  { id:'d113', hora:'00:01', texto:'Rotina Diária - Estoque/Custo Comercial', obs:'Comercial - Após Cfato033 – CFATJ001', caminho:'Serviço Batch/Comercial/Rotina Diária - Estoque/Custo Comercial', secao:'Após meia-noite' },
  { id:'d114', hora:'00:01', texto:'Rotina Diária – Gestão de Safra', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Diária – Gestão de Safra', secao:'Após meia-noite' },
  { id:'d115', hora:'00:01', texto:'Rotina Diária - Liquidação', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Diária - Liquidação', secao:'Após meia-noite' },
  { id:'d116', hora:'00:01', texto:'Corvu Estoque', obs:'Após rotina Comercial e Custo Comercial', caminho:'Serviço Batch/Corvu Estoque', secao:'Após meia-noite' },

  // Carga IEPA/IEPE (após Carga Matrículas e após 00:00h)
  { id:'d117', hora:'00:01', texto:'Carga IEPA/IEPE - 1. Confirma Carga do Movto Produtos Agrícolas', obs:'Informações Executivas', caminho:'Serviço Batch/Informações Executivas/Carga IEPA/IEPE - 1. Confirma Carga do Movto', secao:'Após meia-noite' },
  { id:'d118', hora:'00:01', texto:'Carga IEPA/IEPE - 2. Confirma Pedidos Prod. Embalados', obs:'Executar simultaneamente com itens 4, 5, 6 e 7', caminho:'Serviço Batch/Carga IEPA/IEPE - 2. Confirma Pedidos Prod. Embalados', secao:'Após meia-noite' },
  { id:'d119', hora:'00:01', texto:'Carga IEPA/IEPE - 3. Confirma NFs Prod. Embalados', obs:'Somente após o item 2', caminho:'Serviço Batch/Carga IEPA/IEPE - 3. Confirma NFs Prod. Embalados', secao:'Após meia-noite' },
  { id:'d120', hora:'00:01', texto:'Carga IEPA/IEPE - 4. Confirma CNs Uniface', obs:'Executar simultaneamente com item 2', caminho:'Serviço Batch/Carga IEPA/IEPE - 4. Confirma CNs Uniface', secao:'Após meia-noite' },
  { id:'d121', hora:'00:01', texto:'Carga IEPA/IEPE - 5. Confirma NFs Fatcom', obs:'Executar simultaneamente com item 2', caminho:'Serviço Batch/Carga IEPA/IEPE - 5. Confirma NFs Fatcom', secao:'Após meia-noite' },
  { id:'d122', hora:'00:01', texto:'Carga IEPA/IEPE - 6. Confirma Cristalização', obs:'Executar simultaneamente com item 2', caminho:'Serviço Batch/Carga IEPA/IEPE - 6. Confirma Cristalização', secao:'Após meia-noite' },
  { id:'d123', hora:'00:01', texto:'Carga IEPA/IEPE - 7. PH Médio do Trigo', obs:'Executar simultaneamente com item 2', caminho:'Serviço Batch/Carga IEPA/IEPE - 7. PH Médio do Trigo', secao:'Após meia-noite' },

  { id:'d124', hora:'00:01', texto:'Capital Social / Rotina Diária', obs:'Cooperados - Após 00:00h e o Sipa/Diário', caminho:'Serviço Batch/Cooperados/Capital Social / Rotina Diária', secao:'Após meia-noite' },
  { id:'d125', hora:'00:01', texto:'Rotina Diária (Sincronização DRP)', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária (Sincronização DRP)', secao:'Após meia-noite' },
  { id:'d126', hora:'00:01', texto:'Sincronização Upload DRP Neogrid', obs:'Almoxarifado', caminho:'Serviço Batch/Almoxarifado/Sincronização Upload DRP Neogrid', secao:'Após meia-noite' },
  { id:'d127', hora:'00:01', texto:'Rotina Diária – DPI/SIPA (após meia noite)', obs:'Cooperados/Rotinas Sipa', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária – DPI/SIPA (após meia noite)', secao:'Após meia-noite' },
  { id:'d128', hora:'00:01', texto:'Rotina Diária - Eventos', obs:'Arcam', caminho:'Serviço Batch/Arcam/Rotina Diária - Eventos', secao:'Após meia-noite' },
  { id:'d129', hora:'00:01', texto:'Job Diário Fretes – CFREJ001 (Serviço Batch/Fretes)', obs:'CFREJ001', caminho:'Serviço Batch/Fretes/Job Diário – CFREJ001', secao:'Após meia-noite' },
  { id:'d130', hora:'00:01', texto:'Job Migração dos Dados de Rastreador', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Migração dos Dados de Rastreador', secao:'Após meia-noite' },
  { id:'d131', hora:'00:01', texto:'Fatpem / Job Diário – Fatpem', obs:'', caminho:'Serviço Batch/Fatpem / Job Diário – Fatpem', secao:'Após meia-noite' },
  { id:'d132', hora:'00:01', texto:'Fatpem / Job Diário – Atualização Automática Limite de Crédito', obs:'Não executar como movto de sábado', caminho:'Serviço Batch/Fatpem / Job Diário – Atualização Automática Limite de Crédi', secao:'Após meia-noite' },
  { id:'d133', hora:'00:01', texto:'Fatpem / Job Diário – Gerar tabelas de preços para sim3g', obs:'', caminho:'Serviço Batch/Fatpem / Job Diário – Gerar tabelas de preços para sim3g', secao:'Após meia-noite' },
  { id:'d134', hora:'00:01', texto:'Industrial / Diário – Variação Umidade Soja', obs:'', caminho:'Serviço Batch/Industrial / Diário – Variação Umidade Soja', secao:'Após meia-noite' },
  { id:'d135', hora:'00:01', texto:'Industrial / Diário – Demanda de produção Industrial', obs:'Após término exec corvu indústria aux', caminho:'Serviço Batch/Industrial / Diário – Demanda de produção Industrial', secao:'Após meia-noite' },
  { id:'d136', hora:'00:01', texto:'Industrial / Diário - Conciliação Estoque Comercial', obs:'', caminho:'Serviço Batch/Industrial / Diário - Conciliação Estoque Comercial', secao:'Após meia-noite' },
  { id:'d137', hora:'00:01', texto:'Industrial / Diário - Conciliação Estoque Almoxarifado', obs:'', caminho:'Serviço Batch/Industrial / Diário - Conciliação Estoque Almoxarifado', secao:'Após meia-noite' },
  { id:'d138', hora:'00:01', texto:'Industrial / Diário – Produtos para faturamento de amostra', obs:'', caminho:'Serviço Batch/Industrial / Diário – Produtos para faturamento de amostra', secao:'Após meia-noite' },
  { id:'d139', hora:'00:01', texto:'Geração Diária Carteira Corvu', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Geração Diária Carteira Corvu', secao:'Após meia-noite' },
  { id:'d140', hora:'00:01', texto:'Job Diário Crural - Debcred', obs:'Financeiro/Financiamentos', caminho:'Serviço Batch/Financeiro/Financiamentos/Job Diário Crural - Debcred', secao:'Após meia-noite' },
  { id:'d141', hora:'00:01', texto:'Bloqueio Cliente Base SERPRO', obs:'Financeiro/Análise de Crédito', caminho:'Serviço Batch/Financeiro/Análise de Crédito/Bloqueio Cliente Base SERPRO', secao:'Após meia-noite' },
  { id:'d142', hora:'00:01', texto:'Rotina Diária / Iniciar a Rotina', obs:'Cooperados - No mensal Pfatb129 pode cont rotina', caminho:'Serviço Batch/Cooperados/Rotina Diária / Iniciar a Rotina', secao:'Após meia-noite' },
  { id:'d143', hora:'00:01', texto:'Rotina Diária (Bayer/Basf)', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária (Bayer/Basf)', secao:'Após meia-noite' },
  { id:'d144', hora:'00:01', texto:'Rotina Fertilizantes Corvu', obs:'Cooperados - Antes Bens Fornec. Parte 3', caminho:'Serviço Batch/Cooperados/Rotina Fertilizantes Corvu', secao:'Após meia-noite' },
  { id:'d145', hora:'00:01', texto:'Rotina Diária (Programa Fideliza)', obs:'Cooperados - Movimento dia 10 é demorado', caminho:'Serviço Batch/Cooperados/Rotina Diária (Programa Fideliza)', secao:'Após meia-noite' },
  { id:'d146', hora:'00:01', texto:'Rotina Diária (Corteva/Zoetis)', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária (Corteva/Zoetis)', secao:'Após meia-noite' },
  { id:'d147', hora:'00:01', texto:'Rotina Diária (Conciliação a Granel)', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Diária (Conciliação a Granel)', secao:'Após meia-noite' },

  { id:'d148', hora:'00:30', texto:'Almoxarifado / Rotina Diária', obs:'', caminho:'Serviço Batch/Almoxarifado / Rotina Diária', secao:'Após meia-noite' },

  // ── Sexta-feira ─────────────────────────────────────────────────────
  { id:'d158', hora:'19:00', texto:'Pesquisa.bat / Pesquisa_qrp.bat / Pesquisa_query.bat / Pesquisa_copy_corvuDoc.bat', obs:'F:\\Sistemas\\Corvu_docto - Executar Sexta-feira', caminho:'Serviço Batch/Pesquisa.bat / Pesquisa_qrp.bat / Pesquisa_query.bat / Pesquisa', campo:'pesquisa.bat___ pesquisa_qrp___ pesquisa_query___ copy_corvuDoc___', semStatus:true, secao:'Noite' },
  { id:'d159', hora:'19:00', texto:'Unifacedev05 – R10_coamo_pro_tool_BI', obs:'\\\\Coamo\\fs\\UnifaceDev\\Corporativo\\R10_coamo_pro\\Adm\\Ide 10.4 - Sexta-feira', caminho:'Serviço Batch/Unifacedev05 – R10_coamo_pro_tool_BI', campo:'BI ___', semStatus:true, secao:'Noite' },
  { id:'d160', hora:'19:00', texto:'Unifacedev05 – IDF 9.6 – Bkp Semanal', obs:'Executar Quarta-feira', caminho:'Serviço Batch/Unifacedev05 – IDF 9.6 – Bkp Semanal', secao:'Noite' },
  { id:'d161', hora:'19:00', texto:'Unifacedev05 – IDF 9.6 – Bkp Semanal', obs:'Executar Sexta-feira', caminho:'Serviço Batch/Unifacedev05 – IDF 9.6 – Bkp Semanal', secao:'Noite' },

  // ── Após 03:00h (executar após as 03:00h) ───────────────────────────
  { id:'d149', hora:'03:00', texto:'Contabilidade Diária', obs:'Administrativa/Contabilidade', caminho:'Serviço Batch/Administrativa/Contabilidade/Contabilidade Diária', secao:'Após 03:00h' },
  { id:'d150', hora:'03:00', texto:'Fiação de Algodão / Rotina Diária', obs:'', caminho:'Serviço Batch/Fiação de Algodão / Rotina Diária', secao:'Após 03:00h' },
  { id:'d151', hora:'03:00', texto:'Job Diário – Limpeza Eventos Portaria', obs:'Portaria - Executar após as 03:00h', caminho:'Serviço Batch/Portaria/Job Diário – Limpeza Eventos Portaria', secao:'Após 03:00h' },
  { id:'d152', hora:'03:00', texto:'Industrial / Diário - Conciliação Estoque Fatpem', obs:'Executar entre 03:00h e 04:00h', caminho:'Serviço Batch/Industrial / Diário - Conciliação Estoque Fatpem', secao:'Após 03:00h' },
  { id:'d153', hora:'03:00', texto:'Refaz Saldo Mensal', obs:'Administrativa/Contabilidade - Mês Corrente - Plano 1 - Actm6 fora', caminho:'Serviço Batch/Administrativa/Contabilidade/Refaz Saldo Mensal', secao:'Após 03:00h' },
  { id:'d154', hora:'03:00', texto:'Produtor com débito vencido CORVU', obs:'Cooperados/Rotinas Sipa - Após Carga Corvu Atendimento Produtor', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Produtor com débito vencido CORVU', secao:'Após 03:00h' },

  // ── Acompanhamento Carga BI ─────────────────────────────────────────
  { id:'d155', hora:'03:00', texto:'Carga Diária BI_COAMO - STG', obs:'Acompanhamento', caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - STG', secao:'Acompanhamento BI' },
  { id:'d156', hora:'03:00', texto:'Carga Diária BI_COAMO - DW', obs:'Acompanhamento', caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - DW', secao:'Acompanhamento BI' },
  { id:'d157', hora:'03:00', texto:'Carga Diária BI_COAMO - DM', obs:'Acompanhamento', caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - DM', secao:'Acompanhamento BI' },
];

// Rotinas Corvu Diário
const ROTINAS_CORVU = [
  'Contas a Receber – MSS',
  'Indústria – MSS após 07:00h',
  'Credicoamo – MSS após Job SBAPJ002',
  'Indústria Parte2 08:35h – Após Indústria - MSS',
  'Semente Análises - Almoço Executar 11:55h',
  'Transporte – MSS - Almoço',
  'Segurança Corvu – MSS – Almoço',
  'Credicoamo – Almoço',
  'Produtividade - MSS',
  'Segurança Corvu – MSS',
  'Recursos Humanos – MSS',
  'Financiamento – MSS',
  'Almox/Frota – MSS 20:00h',
  'Pedido Bens Fornecimento – MSS 20:00h',
  'ARCAM / VSOLLUS – MSS',
  'Financeira – Após FAPLJ001 – MSS',
  'Transporte Diário – MSS 23:00h',
  '1 – Cadastro - MSS',
  '2 – Atend. Produtor - Prod. Agríc. - MSS',
  '3 – Atend. Produtor - Prod. Agríc. - Parte 2 - MSS',
  '4 – Atend. Produtor - Cobrança – MSS',
  'Produtos Agrícolas',
  'Atuação Produtor',
  '1 - Cobrança',
  '2 – Sobras - MSS',
  'CREDICOAMO - Eis_Credi_Ora – Após Meia Noite',
  'Bens Fornecimento – MSS – Parte 1 Ap. 00:01',
  'Bens Fornecimento – MSS – Parte 3 Ap. parte 1',
  '1 - Semente – MSS Antes Semente Análises',
  '2 - Semente Análises – após Bens Forn., parte 3',
  'Produtos Agrícolas - MSS',
  'Comercial Parte 1 - MSS',
  'Comercial Parte 2 Alimentos - MSS - após parte 1',
  '1 - Comercial Parte 2 Prodagric - MSS - após parte 1',
  '2 - Raio X Bancos - MSS',
  'Contabilidade - MSS ap. Refaz Saldo',
  'Estoque – MSS lib. CFATJ001 fim CNFO074',
  'Orçado x Realizado Prévia – MSS',
  'Energia Elétrica – dia 01 e 15 - MSS',
];

// Rotinas Uniface Mensal
const ROTINAS_MENSAL = [
  { id:'m1', hora:'Último dia do mês - após 18:00h', texto:'Atualização Contas a Pagar CORVU', obs:'Fornecedores', caminho:'Serviço Batch/Fornecedores/Atualização Contas a Pagar CORVU', secao:'Último dia do mês' },
  { id:'m2', hora:'Último dia do mês - após Diária Cadastro', texto:'Rotina Mensal Cadastro', obs:'Cooperados/Rotinas-Cadastro', caminho:'Serviço Batch/Cooperados/Rotinas-Cadastro/Rotina Mensal Cadastro', secao:'Último dia do mês' },
  { id:'m3', hora:'Último dia - após 21:00h', texto:'Job Mensal de Comprovação', obs:'Financeiro/Financiamentos', caminho:'Serviço Batch/Financeiro/Financiamentos/Job Mensal de Comprovação', secao:'Último dia do mês' },
  { id:'m4', hora:'Último dia - após 23:00h', texto:'Conciliação Mensal – Vales Arcam', obs:'Arcam', caminho:'Serviço Batch/Arcam/Conciliação Mensal – Vales Arcam', secao:'Último dia do mês' },
  { id:'m5', hora:'Após 00:00h', texto:'Geração Mensal Carteira Corvu', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Geração Mensal Carteira Corvu', secao:'Virada do mês' },
  { id:'m6', hora:'Após Rotina Diária Sipa', texto:'Rotina Mensal Sipa', obs:'Cooperados/Rotinas Sipa', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Mensal Sipa', secao:'Virada do mês' },
  { id:'m7', hora:'Após Rotina Mensal Sipa', texto:'Conciliação Debcred', obs:'Cooperados/Rotinas Sipa', caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Conciliação Debcred', secao:'Virada do mês' },
  { id:'m8', hora:'Após Rotina Diária Capital Social', texto:'Rotina Mensal Capital Social', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Rotina Mensal Capital Social', secao:'Virada do mês' },
  { id:'m9', hora:'Após Rotina/Diária Fatloj', texto:'Job Mensal – Inventário', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Job Mensal – Inventário', secao:'Virada do mês' },
  { id:'m10', hora:'Após todos botões Corvu Diário', texto:'Atualiza Data Mensal do IEPA', obs:'Informação Exec./Carga IEPA/IEPE - Antes do Corvu Mensal', caminho:'Serviço Batch/Informações Executivas/Atualiza Data Mensal do IEPA', secao:'Virada do mês' },
  { id:'m11', hora:'Após Job Diário Fatpem', texto:'Job Mensal – Comissão do Fatpem', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Job Mensal – Comissão do Fatpem', secao:'Virada do mês' },
  { id:'m12', hora:'Após Rotina Diária Sistema Comercial', texto:'Rotina Mensal – Sist. Comercial', obs:'Comercial', caminho:'Serviço Batch/Comercial/Rotina Mensal – Sist. Comercial', secao:'Virada do mês' },
  { id:'m13', hora:'Após Mensal Comissão Fatpem e Comercial', texto:'Conciliação da Comissão (Mensal)', obs:'Comissão', caminho:'Serviço Batch/Comissão/Conciliação da Comissão (Mensal)', secao:'Virada do mês' },
  { id:'m14', hora:'Virada do mês', texto:'Rotina Batch Mensal', obs:'Sementes', caminho:'Serviço Batch/Sementes/Rotina Batch Mensal', secao:'Virada do mês' },
  { id:'m15', hora:'Primeiro dia do mês', texto:'Job Mensal – Gera arquivo DME caixa', obs:'Financeiro/Caixa', caminho:'Serviço Batch/Financeiro/Caixa/Job Mensal – Gera arquivo DME caixa', secao:'Primeiro dia do mês' },
  { id:'m16', hora:'Primeiro dia do mês', texto:'Emissão de Relatório Mensal CEFxDebcred', obs:'Cooperados', caminho:'Serviço Batch/Cooperados/Emissão de Relatório Mensal CEFxDebcred', secao:'Primeiro dia do mês' },
  { id:'m17', hora:'Primeiro dia útil', texto:'Mensal – Conciliação Fatpem-Caixa', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Mensal – Conciliação Fatpem-Caixa', secao:'Primeiro dia do mês' },
  { id:'m18', hora:'Primeiro dia útil', texto:'Geração Carteiras Conciliação', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Geração Carteiras Conciliação', secao:'Primeiro dia do mês' },
  { id:'m19', hora:'Primeiro dia do mês', texto:'Carteira Conciliação CEF', obs:'Cooperados - Gera Arquivo', caminho:'Serviço Batch/Cooperados/Carteira Conciliação CEF', secao:'Primeiro dia do mês' },
  { id:'m20', hora:'Primeiro dia do mês', texto:'Corvu ACTM_CUSTOS + Carga Preço Médios', obs:'Informações Executivas', caminho:'Serviço Batch/Informações Executivas/Corvu ACTM_CUSTOS + Carga Preço Médios', secao:'Primeiro dia do mês' },
  { id:'m21', hora:'Primeiro dia útil', texto:'Mensal Seguros', obs:'Financeiro/Seguros', caminho:'Serviço Batch/Financeiro/Seguros/Mensal Seguros', secao:'Primeiro dia do mês' },
  { id:'m22', hora:'Primeiro dia do mês', texto:'Rotina Mensal Seguro Prestamista + Prestamista Rotativo', obs:'Cooperados - Não executar junto com job Diário Crédito Rural', caminho:'Serviço Batch/Cooperados/Rotina Mensal Seguro Prestamista + Prestamista Rot', secao:'Primeiro dia do mês' },
  { id:'m23', hora:'Primeiro dia útil', texto:'Job Mensal Controle Bancário', obs:'Financeiro', caminho:'Serviço Batch/Financeiro/Job Mensal Controle Bancário', secao:'Primeiro dia do mês' },
  { id:'m24', hora:'Primeiro dia útil', texto:'Impressão - Índices de Inadimplência', obs:'Financeiro/Contas a Receber', caminho:'Serviço Batch/Financeiro/Contas a Receber/Impressão - Índices de Inadimplência', secao:'Primeiro dia do mês' },
  { id:'m25', hora:'Após liberação', texto:'Job Mensal Caixa', obs:'Financeiro/Caixa', caminho:'Serviço Batch/Financeiro/Caixa/Job Mensal Caixa', secao:'Após liberação' },
  { id:'m26', hora:'Após liberação', texto:'Mensal Fiscal', obs:'Administrativa/Fiscal', caminho:'Serviço Batch/Administrativa/Fiscal/Mensal Fiscal', secao:'Após liberação' },
  { id:'m27', hora:'Após liberação', texto:'Rotina Mensal - Sist. Fccia', obs:'Administrativa/Fccia - 21:00h', caminho:'Serviço Batch/Administrativa/Fccia/Rotina Mensal - Sist. Fccia', secao:'Após liberação' },
  { id:'m28', hora:'Após liberação', texto:'Geração de Ficha Fccia', obs:'Administrativa/Fccia', caminho:'Serviço Batch/Administrativa/Fccia/Geração de Ficha Fccia', secao:'Após liberação' },
  { id:'m29', hora:'Após liberação', texto:'Mensal Ciap / Job Mensal de Parcelamento', obs:'Administrativa/Ciap', caminho:'Serviço Batch/Administrativa/Ciap/Mensal Ciap / Job Mensal de Parcelamento', secao:'Após liberação' },
  { id:'m30', hora:'Após liberação', texto:'Mensal Ciap - Contabilização do Ciap', obs:'Administrativa/Ciap', caminho:'Serviço Batch/Administrativa/Ciap/Mensal Ciap - Contabilização do Ciap', secao:'Após liberação' },
  { id:'m31', hora:'Quando solicitado', texto:'Mensal Patrimônio + Depreciação Gerencial Patrimônio', obs:'Administrativa/Contabilidade - Executar primeiro rotina diária do Patrimônio', caminho:'Serviço Batch/Administrativa/Contabilidade/Mensal Patrimônio + Depreciação Ge', secao:'Quando solicitado' },
  { id:'m32', hora:'Após Contabilização da Folha', texto:'Job Apuração do Tku', obs:'Transporte', caminho:'Serviço Batch/Transporte/Job Apuração do Tku', secao:'Quando solicitado' },
  { id:'m33', hora:'Após liberação Fiscal', texto:'SPED Fiscal - Geração de Arquivos Mensais – Carga Unidades', obs:'Administrativa/Fiscal', caminho:'Serviço Batch/Administrativa/Fiscal/SPED Fiscal - Geração de Arquivos Mensais', secao:'Quando solicitado' },
  { id:'m34', hora:'Dia 05', texto:'Cotação das Bolsas na TV', obs:'ADMCMA02', caminho:'Serviço Batch/Cotação das Bolsas na TV', secao:'Datas específicas' },
  { id:'m35', hora:'Dia 10', texto:'JOB Mensal – Importação Base SERPRO', obs:'Financeiro/Análise de Crédito', caminho:'Serviço Batch/Financeiro/Análise de Crédito/JOB Mensal – Importação Base SERPRO', secao:'Datas específicas' },
  { id:'m36', hora:'Após dia 10', texto:'Mensal - Geração Arquivo NF Exportação', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Mensal - Geração Arquivo NF Exportação', secao:'Datas específicas' },
];

// Rotinas Unimed
const ROTINAS_UNIMED = [
  { id:'u1', hora:'Dia 10 após 18:00h', texto:'Rotina Unimed Rural - Gera Arquivo de Usuários Co-participativo', obs:'Gera arquivo U183xxx.183 - Enviar Unimed | Admfs02\\corporativo_des\\produção\\arquivos\\pseg', caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Unimed Rural - Gera Arquivo de', secao:'Dia 10' },
  { id:'u2', hora:'Dia 10 após 18:00h', texto:'Rotina Unimed Rural Co-participativo - Gera Comissões Unimed Co-participativo', obs:'Gera as comissões do mês do plano', caminho:'Serviço Batch/Rotina Unimed Rural Co-participativo - Gera Comissões Unimed Co-', secao:'Dia 10' },
  { id:'u3', hora:'Dia 10 após 18:00h', texto:'Rotina Unimed Coamo Essencial - Gera Arquivos de Movimentações Para Unimed', obs:'Gera arquivo U183xxx.183 – Enviar', caminho:'Serviço Batch/Rotina Unimed Coamo Essencial - Gera Arquivos de Movimentações', secao:'Dia 10' },
  { id:'u4', hora:'Dia 10 após 18:00h', texto:'Rotina Unimed Coamo Essencial - Gera Faturamento Mensal', obs:'', caminho:'Serviço Batch/Rotina Unimed Coamo Essencial - Gera Faturamento Mensal', secao:'Dia 10' },
  { id:'u5', hora:'Dia 10 - Após receber arquivo Unimed Essencial (MENmmaa.txt e SERmmaa.txt)', texto:'Ler Arquivo Fat. Unimed (Mensalidades)', obs:'', caminho:'Serviço Batch/Ler Arquivo Fat. Unimed (Mensalidades)', secao:'Dia 10' },
  { id:'u6', hora:'Dia 10 - Após receber arquivo', texto:'Ler Arquivo Fat. Unimed (Serviços)', obs:'Executar sem arquivo', caminho:'Serviço Batch/Ler Arquivo Fat. Unimed (Serviços)', secao:'Dia 10' },
  { id:'u7', hora:'Dia 10 - Após receber arquivo', texto:'Organizar Arquivos', obs:'', caminho:'Serviço Batch/Organizar Arquivos', secao:'Dia 10' },
  { id:'u8', hora:'Dia 10 após 18:00h', texto:'Atualizar Diretórios – Adesão', obs:'', caminho:'Serviço Batch/Atualizar Diretórios – Adesão', secao:'Dia 10' },
  { id:'u9', hora:'Dia 10 após 18:00h', texto:'Atualizar Diretórios Rural', obs:'Copia os arquivos para a pasta PSEG/aaaamm', caminho:'Serviço Batch/Atualizar Diretórios Rural', secao:'Dia 10' },
  { id:'u10', hora:'Dia 15 após 18:00h', texto:'Rotina Unimed Co-participativo Adesão - Gera Movimentação Usuários/Contratante', obs:'\\pseg\\adesão\\...... Enviar Unimed', caminho:'Serviço Batch/Rotina Unimed Co-participativo Adesão - Gera Movimentação Usuár', secao:'Dia 15' },
  { id:'u11', hora:'Dia 15 após 18:00h', texto:'Rotina Unimed Co-participativo Adesão - Gera Faturamento Mensal Unimed', obs:'', caminho:'Serviço Batch/Rotina Unimed Co-participativo Adesão - Gera Faturamento Mensal', secao:'Dia 15' },
  { id:'u12', hora:'Dia 15 - Após receber arquivo ADESÃO', texto:'Ler Arquivo Faturamento Mensalidades', obs:'MENmmaa.txt – RemissaoMMAA.txt | Salvar em K:/corporativo_des/produção/arquivos/pseg/adesão', caminho:'Serviço Batch/Ler Arquivo Faturamento Mensalidades', secao:'Dia 15' },
  { id:'u13', hora:'Dia 15 - Após receber arquivo', texto:'Ler Arquivo Faturamento dos Serviços', obs:'SERmmaa.txt', caminho:'Serviço Batch/Ler Arquivo Faturamento dos Serviços', secao:'Dia 15' },
  { id:'u14', hora:'Dia 15 - Após receber arquivos', texto:'Concilia/Carga Comissão Paga', obs:'Comissão Coamo mmaaaa.txt | Salvar em K:/corporativo_des/produção/arquivos/pseg', caminho:'Serviço Batch/Comissão/Concilia/Carga Comissão Paga', secao:'Dia 15' },
  { id:'u15', hora:'Dia 15 - Após receber arquivos', texto:'Concilia/Carga Comissão Aberta', obs:'Abertos mmaaaa.txt', caminho:'Serviço Batch/Concilia/Carga Comissão Aberta', secao:'Dia 15' },
  { id:'u16', hora:'Dia 15 - Após receber arquivos', texto:'Concilia/Carga Comissão Migração', obs:'Migrações mmaaaa.txt – sem arquivo processar', caminho:'Serviço Batch/Concilia/Carga Comissão Migração', secao:'Dia 15' },
  { id:'u17', hora:'Dia 20 a 21', texto:'Rotina Unimed Rural - Gera Movimentação Usuários/Contratante', obs:'Gera arquivo U183xxxx.183 - Enviar Unimed', caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Unimed Rural - Gera Movimentaçã', secao:'Dia 20-25' },
  { id:'u18', hora:'Dia 20 a 21', texto:'Rotina Unimed Rural - Gera Faturamento Mensal Unimed', obs:'', caminho:'Serviço Batch/Rotina Unimed Rural - Gera Faturamento Mensal Unimed', secao:'Dia 20-25' },
  { id:'u19', hora:'Dia 20 a 25 - Após receber arquivo', texto:'Ler Arquivo Faturamento Mensal Unimed', obs:'Lê arquivo FATmmaa.TXT / Renomear Reemissão para RemissaoMMAA.txt | Se divergência: e-mail para Jeferson(Gerac) | Salvar em K:/corporativo_des/produção/arquivos/pseg', caminho:'Serviço Batch/Ler Arquivo Faturamento Mensal Unimed', secao:'Dia 20-25' },
  { id:'u20', hora:'Após acerto inconsistência', texto:'Rotina Diária – UNIMED (executar à noite)', obs:'Serviço Batch/Cooperados/Rotina Diária – Unimed', caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Diária – UNIMED (executar à noi', secao:'Dia 20-25' },
  { id:'u21', hora:'Diária', texto:'Rotina Diária Unimed', obs:'Gera Arquivo - Sistemas/Cooperados/Unimed/Skyline/Unimed/outbox/COA0000X..ret | Enviar via SKYLINE | E-mail: jeniffer@unimedcampomourao.com.br / talita@unimedcampomourao.com.br', caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Diária Unimed', secao:'Rotina Diária' },
];

// Rotinas Serasa
const ROTINAS_SERASA = [
  { id:'s1', hora:'A cada 15 dias após 00:00h', texto:'Conectar no Site SERASA – Produto 085', obs:'K:\\Corporativo_des\\Produção\\Arquivos\\Cser\\Serasa.txt | Site: https://st.serasaexperian.com.br – P6044 – L2G5RqxE | Tel: (11) 2847-9900', caminho:'Serviço Batch/Conectar no Site SERASA – Produto 085', secao:'Rotina Quinzenal' },
  { id:'s2', hora:'A cada 15 dias após 00:00h', texto:'Quinz. - SERASA String Relato Analítico', obs:'Fatpem', caminho:'Serviço Batch/Fatpem/Quinz. - SERASA String Relato Analítico', secao:'Rotina Quinzenal' },
  { id:'s3', hora:'05/04/2026', texto:'Job Semanal Serasa Remessa', obs:'Envio arquivo / Renomear arquivo | Arquivo: \\\\coamo\\fs\\coamo\\prod\\scac\\arquivos\\serasa_envio_deb.txt | Renomear: serasa_envio_deb_rem_ddmmaaaa.txt', caminho:'Serviço Batch/Job Semanal Serasa Remessa', secao:'Abril 2026' },
  { id:'s4', hora:'05/04/2026', texto:'Receber arquivo e verificar inconsistência', obs:'Produto 012', caminho:'Serviço Batch/Receber arquivo e verificar inconsistência', secao:'Abril 2026' },
  { id:'s5', hora:'12/04/2026', texto:'Job Semanal Serasa Remessa', obs:'Envio arquivo / Renomear arquivo', caminho:'Serviço Batch/Job Semanal Serasa Remessa', secao:'Abril 2026' },
  { id:'s6', hora:'12/04/2026', texto:'Receber arquivo e verificar inconsistência', obs:'', caminho:'Serviço Batch/Receber arquivo e verificar inconsistência', secao:'Abril 2026' },
  { id:'s7', hora:'12/04/2026 - Conciliação', texto:'Receber arquivo Conciliação Serasa', obs:'Renomear: serasa_receb_deb.txt | Arquivo em: \\\\coamo\\fs\\coamo\\prod\\scac\\arquivos\\ | Após rotina remessa - Domingo após segundo sábado do mês', caminho:'Serviço Batch/Receber arquivo Conciliação Serasa', secao:'Conciliação' },
  { id:'s8', hora:'12/04/2026 - Conciliação', texto:'Job Semanal Serasa Conciliação', obs:'Enviar arquivo / Renomear: serasa_envio_deb_conc_ddmmaaaa.txt | Arquivo: \\\\coamo\\fs\\coamo\\prod\\scac\\arquivos\\serasa_envio_deb.txt', caminho:'Serviço Batch/Job Semanal Serasa Conciliação', secao:'Conciliação' },
  { id:'s9', hora:'12/04/2026 - Conciliação', texto:'Receber arquivo e verificar inconsistência', obs:'', caminho:'Serviço Batch/Receber arquivo e verificar inconsistência', secao:'Conciliação' },
  { id:'s10', hora:'19/04/2026', texto:'Job Semanal Serasa Remessa', obs:'Envio arquivo / Renomear arquivo', caminho:'Serviço Batch/Job Semanal Serasa Remessa', secao:'Abril 2026' },
  { id:'s11', hora:'19/04/2026', texto:'Receber arquivo e verificar inconsistência', obs:'', caminho:'Serviço Batch/Receber arquivo e verificar inconsistência', secao:'Abril 2026' },
  { id:'s12', hora:'26/04/2026', texto:'Job Semanal Serasa Remessa', obs:'Envio arquivo / Renomear arquivo', caminho:'Serviço Batch/Job Semanal Serasa Remessa', secao:'Abril 2026' },
  { id:'s13', hora:'26/04/2026', texto:'Receber arquivo e verificar inconsistência', obs:'', caminho:'Serviço Batch/Receber arquivo e verificar inconsistência', secao:'Abril 2026' },
];

// Rotinas Corvu Mensal
// Executar somente após atualizar a data mensal do IEPA
const ROTINAS_CORVU_MENSAL = [
  { nome: 'Contas a Pagar - MSS', obs: 'Após atualizar data e Uniface Atualização Contas a Pagar Corvu' },
  { nome: 'Almoxarifado - MSS', obs: 'Após Corvu Diário Almox/Frota e após atualizar a data' },
  { nome: 'Frota - MSS', obs: 'Último dia do mês após atualizar a data' },
  { nome: '1 - Produtos Agrícolas - MSS', obs: 'Após Uniface - Atualiza data mensal do IEPA' },
  { nome: '2 - Atuação Unidades - MSS', obs: 'Após Uniface - Atualiza data mensal do IEPA' },
  { nome: 'Bens de Fornecimento - MSS', obs: '' },
  { nome: 'Cobrança - MSS - ap. Bens Fornec-MSS', obs: '' },
  { nome: 'Cobrança - após cobrança - MSS', obs: '' },
  { nome: 'Com. Representante - MSS', obs: 'Após Uniface Mensal – Comissão do Fatpem e Cobrança Mensal – MSS' },
  { nome: 'Credicoamo Mensal - MSS', obs: '' },
  { nome: 'Imobilizado - MSS', obs: '' },
  { nome: 'Geral - MSS – Após mensal do Prestamista', obs: 'Após Rotina Mensal Prestamista' },
  { nome: 'Recursos Humanos – MSS – Após job06 RH', obs: 'Após contabilização da Folha de Pagamento' },
];

// ── Rotinas Final de Semana (Sábado Noite → Domingo) ─────────────────
const ROTINAS_FDS_NOVO = [

  // ════════════ SÁBADO NOITE — Após 19:00h ════════════
  { id:'fn1',  hora:'19:00', texto:'Rotina Diária - DRP',                                          caminho:'Serviço Batch/Cooperados/Rotina Diária - DRP',                                              obs:'Cooperados',                                    secao:'Sábado Noite' },
  { id:'fn2',  hora:'19:00', texto:'Rotina Batch Diária Envio de Notificação – Gestão Reclamação de Sementes', caminho:'Serviço Batch/Sementes/Rotina Batch Diária Envio de Notificação',              obs:'Sementes',                                      secao:'Sábado Noite' },
  { id:'fn3',  hora:'19:00', texto:'Rotina Semanal Necessidade Estoque',                           caminho:'Serviço Batch/Fornecedores/Rotina Semanal Necessidade Estoque',                             obs:'Fornecedores',                                  secao:'Sábado Noite' },
  { id:'fn4',  hora:'19:00', texto:'Job Cálculo do Prêmio de Produção',                            caminho:'Serviço Batch/Transporte/Job Cálculo do Prêmio de Produção',                               obs:'Transporte',                                    secao:'Sábado Noite' },
  { id:'fn5',  hora:'19:00', texto:'Emissão de Relatórios Batch',                                  caminho:'Serviço Batch/Cooperados/Emissão de Relatórios Batch',                                      obs:'Cooperados',                                    secao:'Sábado Noite' },
  { id:'fn6',  hora:'19:00', texto:'Rotina Diária Mobilidade',                                     caminho:'Serviço Batch/Astec/Rotina Diária Mobilidade',                                              obs:'Astec',                                         secao:'Sábado Noite' },
  { id:'fn7',  hora:'19:00', texto:'Rotina Diária Ass. Técnica Cooperado',                         caminho:'Serviço Batch/Astec/Rotina Diária Ass. Técnica Cooperado',                                  obs:'Astec',                                         secao:'Sábado Noite' },
  { id:'fn8',  hora:'19:00', texto:'Rotina Diária RH',                                             caminho:'Serviço Batch/Recursos Humanos/Rotina Diária',                                              obs:'Recursos Humanos',                              secao:'Sábado Noite' },
  { id:'fn9',  hora:'19:00', texto:'Rotina Diária eSocial',                                        caminho:'Serviço Batch/eSocial/Rotina Diária',                                                       obs:'eSocial',                                       secao:'Sábado Noite' },
  { id:'fn10', hora:'19:00', texto:'Rotina Diária Unimed',                                         caminho:'Serviço Batch/Cooperados/Rotinas Unimed/Rotina Diária',                                     obs:'Gera Arquivo: Sistemas/Cooperados/Unimed/Skyline/Unimed/outbox/COA0000X..ret | Enviar via SKYLINE', secao:'Sábado Noite' },
  { id:'fn11', hora:'19:00', texto:'Rotina Diária (Metas de Fornecimentos de Insumos)',             caminho:'Serviço Batch/Cooperados/Rotina Diária (Metas de Fornecimentos de Insumos)',                obs:'Cooperados',                                    secao:'Sábado Noite' },
  { id:'fn12', hora:'19:00', texto:'Rotina Diária Cadastro',                                       caminho:'Serviço Batch/Cooperados/Rotinas-Cadastro/Rotina Diária',                                   obs:'Cooperados', campo:'Pcad ___',                  secao:'Sábado Noite' },
  { id:'fn13', hora:'19:00', texto:'Rotina Diária Auxiliar - Cadastro',                            caminho:'Serviço Batch/Cooperados/Rotinas-Cadastro/Rotina Diária Auxiliar - Cadastro',               obs:'Cooperados',                                    secao:'Sábado Noite' },

  // ════════════ SÁBADO NOITE — Após 20:00h ════════════
  { id:'fn14', hora:'20:00', texto:'Job Programação Automática',                                   caminho:'Serviço Batch/Transporte/Job Programação Automática',                                       obs:'Transporte',                                    secao:'Sábado Noite' },
  { id:'fn15', hora:'20:00', texto:'Sincronização Download DRP Neogrid',                           caminho:'Serviço Batch/Almoxarifado/Sincronização Download DRP Neogrid',                             obs:'Almoxarifado',                                  secao:'Sábado Noite' },

  // ════════════ SÁBADO NOITE — Após 21:00h ════════════
  { id:'fn16', hora:'21:00', texto:'Rotina Diária IBM Máximo',                                     caminho:'Serviço Batch/Fornecedores/Rotina Diária IBM Máximo',                                       obs:'Fornecedores',                                  secao:'Sábado Noite' },
  { id:'fn17', hora:'21:00', texto:'Rotina Diária TV - Previsão Tempo',                            caminho:'Serviço Batch/Cooperados/Rotina Diária TV',                                                 obs:'Cooperados',                                    secao:'Sábado Noite' },
  { id:'fn18', hora:'21:00', texto:'Rotina Diária Sipa',                                           caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária',                                       obs:'Cooperados/Rotinas Sipa',                       secao:'Sábado Noite' },
  { id:'fn19', hora:'21:00', texto:'Rotina Diária Auxiliar - SIPA',                                caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária Auxiliar - SIPA',                       obs:'Cooperados/Rotinas Sipa',                       secao:'Sábado Noite' },
  { id:'fn20', hora:'21:00', texto:'Carga Matrículas',                                             caminho:'Serviço Batch/Informações Executivas/Carga Matrículas',                                     obs:'Informações Executivas - Após Rotina diária do Sipa', secao:'Sábado Noite' },

  // ════════════ SÁBADO NOITE — Após 21:30h ════════════
  { id:'fn21', hora:'21:30', texto:'Rotina Diária Gestão Crédito',                                 caminho:'Serviço Batch/Via Sollus/Rotina Diária Gestão Crédito',                                     obs:'Via Sollus',                                    secao:'Sábado Noite' },

  // ════════════ SÁBADO NOITE — Após 23:00h ════════════
  { id:'fn22', hora:'23:00', texto:'Job Diário – Identif. e Notif. de Anomalias',                  caminho:'Serviço Batch/Sistema/Job Diário – Identif. e Notif. de Anomalias',                         obs:'Sistema',                                       secao:'Sábado Noite' },
  { id:'fn23', hora:'23:00', texto:'Rotina Diária Controle e Integração Defensivos',               caminho:'Serviço Batch/Astec/Rotina Diária Controle e Integração Defensivos',                        obs:'Astec',                                         secao:'Sábado Noite' },
  { id:'fn24', hora:'23:00', texto:'Rotina Diária Fornecedores',                                   caminho:'Serviço Batch/Fornecedores/Rotina Diária',                                                  obs:'Fornecedores',                                  secao:'Sábado Noite' },
  { id:'fn25', hora:'23:00', texto:'Rotina Diária Memoriais',                                      caminho:'Serviço Batch/Administrativa/Projetos e Memoriais/Rotina Diária Memoriais',                  obs:'Executar no feriado',                           secao:'Sábado Noite' },

  // ════════════ SÁBADO VIRADA — Após 23:50h ════════════
  { id:'fn26', hora:'23:50', texto:'Diário - Geração NF Transferência',                            caminho:'Serviço Batch/Fatpem/Diário - Geração NF Transferência',                                    obs:'Fatpem - Antes das 00:00h',                     secao:'Sábado Virada' },

  // ════════════ SÁBADO VIRADA — Após 00:01h ════════════
  { id:'fn27', hora:'00:01', texto:'Rotina Diária - Sistema Comercial',                            caminho:'Serviço Batch/Comercial/Rotina Diária – Sist. Comercial',                                   obs:'Comercial - Corvu Estoque',                     secao:'Sábado Virada' },
  { id:'fn28', hora:'00:01', texto:'Rotina Diária - Sistema Comercial AVV',                        caminho:'Serviço Batch/Comercial/Rotina Diária - Sistema Comercial AVV',                             obs:'Comercial',                                     secao:'Sábado Virada' },
  { id:'fn29', hora:'00:01', texto:'Rotina Diária - Sist. Comercial Oper. Exportação',             caminho:'Serviço Batch/Comercial/Rotina Diária - Sist. Comercial Oper. Exportação',                  obs:'Comercial',                                     secao:'Sábado Virada' },
  { id:'fn30', hora:'00:01', texto:'Rotina Diária - Estoque/Custo Comercial',                      caminho:'Serviço Batch/Comercial/Rotina Diária - Estoque/Custo Comercial',                           obs:'Comercial - Após Cfato033',                     secao:'Sábado Virada' },
  { id:'fn31', hora:'00:01', texto:'Rotina Diária – Gestão de Safra',                              caminho:'Serviço Batch/Comercial/Rotina Diária – Gestão de Safra',                                   obs:'Comercial',                                     secao:'Sábado Virada' },
  { id:'fn32', hora:'00:01', texto:'Rotina Diária - Liquidação',                                   caminho:'Serviço Batch/Comercial/Rotina Diária - Liquidação',                                        obs:'Comercial',                                     secao:'Sábado Virada' },
  { id:'fn33', hora:'00:01', texto:'Rotina Diária - Eventos',                                      caminho:'Serviço Batch/Arcam/Rotina Diária - Eventos',                                               obs:'Arcam - Após 00:00h',                           secao:'Sábado Virada' },
  { id:'fn34', hora:'00:01', texto:'Industrial / Diário – Demanda de produção Industrial',         caminho:'Serviço Batch/Industrial/Diário – Demanda de produção Industrial',                          obs:'Industrial',                                    secao:'Sábado Virada' },
  { id:'fn35', hora:'00:01', texto:'Industrial / Diário – Variação Umidade Soja',                  caminho:'Serviço Batch/Industrial/Diário – Variação Umidade Soja',                                   obs:'Industrial',                                    secao:'Sábado Virada' },
  { id:'fn36', hora:'00:01', texto:'Industrial / Diário - Conciliação Estoque Comercial',          caminho:'Serviço Batch/Industrial/Diário - Conciliação Estoque Comercial',                           obs:'Industrial',                                    secao:'Sábado Virada' },
  { id:'fn37', hora:'00:01', texto:'Industrial / Diário - Conciliação Estoque Almoxarifado',       caminho:'Serviço Batch/Industrial/Diário - Conciliação Estoque Almoxarifado',                        obs:'Industrial',                                    secao:'Sábado Virada' },
  { id:'fn38', hora:'00:01', texto:'Industrial / Diário – Produtos para faturamento de amostra',   caminho:'Serviço Batch/Industrial/Diário – Produtos para faturamento de amostra',                    obs:'Industrial',                                    secao:'Sábado Virada' },
  { id:'fn39', hora:'00:01', texto:'Rotina Diária (Sincronização DRP)',                            caminho:'Serviço Batch/Cooperados/Rotina Diária (Sincronização DRP)',                                obs:'Cooperados',                                    secao:'Sábado Virada' },
  { id:'fn40', hora:'00:01', texto:'Sincronização Upload DRP Neogrid',                             caminho:'Serviço Batch/Almoxarifado/Sincronização Upload DRP Neogrid',                               obs:'Almoxarifado',                                  secao:'Sábado Virada' },
  { id:'fn41', hora:'00:01', texto:'Job Migração dos Dados de Rastreador',                         caminho:'Serviço Batch/Transporte/Job Migração dos Dados de Rastreador',                             obs:'Transporte',                                    secao:'Sábado Virada' },
  { id:'fn42', hora:'00:01', texto:'Rotina Diária – DPI/SIPA (após meia noite)',                   caminho:'Serviço Batch/Cooperados/Rotinas Sipa/Rotina Diária – DPI/SIPA',                           obs:'Cooperados/Rotinas Sipa - Após meia noite',     secao:'Sábado Virada' },
  { id:'fn43', hora:'00:01', texto:'Capital Social / Rotina Diária',                               caminho:'Serviço Batch/Cooperados/Capital Social/Rotina Diária',                                     obs:'Cooperados - Após 00:00h e o Sipa/Diário',     secao:'Sábado Virada' },
  { id:'fn44', hora:'00:01', texto:'Rotina Diária / Iniciar a Rotina',                             caminho:'Serviço Batch/Cooperados/Rotina Diária/Iniciar a Rotina',                                   obs:'Cooperados - No mensal Pfatb129 pode cont rotina', secao:'Sábado Virada' },
  { id:'fn45', hora:'00:01', texto:'Rotina Diária (Bayer/Basf)',                                   caminho:'Serviço Batch/Cooperados/Rotina Diária (Bayer/Basf)',                                       obs:'Cooperados',                                    secao:'Sábado Virada' },
  { id:'fn46', hora:'00:01', texto:'Rotina Diária (Programa Fideliza)',                            caminho:'Serviço Batch/Cooperados/Rotina Diária (Programa Fideliza)',                                obs:'Cooperados - Movimento dia 10 é demorado',      secao:'Sábado Virada' },
  { id:'fn47', hora:'00:01', texto:'Rotina Diária (Corteva/Zoetis)',                               caminho:'Serviço Batch/Cooperados/Rotina Diária (Corteva/Zoetis)',                                   obs:'Cooperados',                                    secao:'Sábado Virada' },
  { id:'fn48', hora:'00:01', texto:'Rotina Diária (Conciliação a Granel)',                         caminho:'Serviço Batch/Cooperados/Rotina Diária (Conciliação a Granel)',                             obs:'Cooperados',                                    secao:'Sábado Virada' },
  { id:'fn49', hora:'00:01', texto:'Carga IEPA/IEPE - 1. Confirma Carga do Movto Produtos Agrícolas', caminho:'Serviço Batch/Informações Executivas/Carga IEPA/IEPE - 1',                             obs:'Corvu - Atend. Prod. - Prod. Agric.',           secao:'Sábado Virada' },
  { id:'fn50', hora:'00:01', texto:'Carga IEPA/IEPE - 2. Confirma CNs Uniface',                    caminho:'Serviço Batch/Carga IEPA/IEPE - 2. Confirma CNs Uniface',                                  obs:'',                                              secao:'Sábado Virada' },
  { id:'fn51', hora:'00:01', texto:'Carga IEPA/IEPE - 3. Confirma NFs Fatcom',                     caminho:'Serviço Batch/Carga IEPA/IEPE - 3. Confirma NFs Fatcom',                                   obs:'Corvu – Estoque',                               secao:'Sábado Virada' },

  // ════════════ SÁBADO VIRADA — Após 03:00h ════════════
  { id:'fn52', hora:'03:00', texto:'Job Diário – Limpeza Eventos Portaria',                        caminho:'Serviço Batch/Portaria/Job Diário – Limpeza Eventos Portaria',                              obs:'Portaria - Executar após as 03:00h',            secao:'Sábado Virada' },

  // ════════════ CORVU SÁBADO ════════════
  { id:'fn53', hora:'—',     texto:'1 - Atend. Produtor - Prod. Agríc. - MSS',                     caminho:'Corvu/1 - Atend. Produtor - Prod. Agríc. - MSS',                                           obs:'Corvu',                                         secao:'Corvu Sábado' },
  { id:'fn54', hora:'—',     texto:'2 - Atend. Produtor – Prod. Agric - Parte 2 - MSS',            caminho:'Corvu/2 - Atend. Produtor – Prod. Agric - Parte 2 - MSS',                                  obs:'Corvu',                                         secao:'Corvu Sábado' },
  { id:'fn55', hora:'—',     texto:'Estoque - MSS',                                                caminho:'Corvu/Estoque - MSS',                                                                       obs:'Corvu',                                         secao:'Corvu Sábado' },

  // ════════════ DOMINGO MANHÃ ════════════
  { id:'fn56', hora:'04:00', texto:'Integração de Crachá Motorista (Ronda/Cielo)',                 caminho:'Serviço Batch/Recursos Humanos/Integração de Crachá Motorista (Ronda/Cielo)',               obs:'RH - Domingo às 04:00h',                        secao:'Domingo Manhã' },
  { id:'fn57', hora:'05:00', texto:'Bloqueio Cliente Base CISP',                                   caminho:'Serviço Batch/Financeiro/Análise de Crédito/Bloqueio Cliente Base CISP',                    obs:'Financeiro/Análise de Crédito',                 secao:'Domingo Manhã' },
  { id:'fn58', hora:'05:00', texto:'Bloqueio Cliente Base SERPRO',                                 caminho:'Serviço Batch/Financeiro/Análise de Crédito/Bloqueio Cliente Base SERPRO',                  obs:'Financeiro/Análise de Crédito',                 secao:'Domingo Manhã' },
  { id:'fn59', hora:'05:30', texto:'Rotina Sincronização Realizado Diária',                        caminho:'Serviço Batch/Cooperados/Rotina Sincronização Realizado Diária',                            obs:'Cooperados - Após BI DM',                       secao:'Domingo Manhã' },
  { id:'fn60', hora:'06:00', texto:'Job-APSs Diário - Moinho e Gordurosos',                        caminho:'Serviço Batch/Industrial/Job-APSs Diário - Moinho e Gordurosos',                           obs:'Industrial',                                    secao:'Domingo Manhã' },
  { id:'fn61', hora:'06:00', texto:'Job-APSs Diário - Ração',                                      caminho:'Serviço Batch/Industrial/Job-APSs Diário - Ração',                                         obs:'Industrial',                                    secao:'Domingo Manhã' },
  { id:'fn62', hora:'06:00', texto:'Rotina Sincronização Download Pedidos Neogrid',                caminho:'Serviço Batch/Cooperados/Rotina Sincronização Download Pedidos Neogrid',                    obs:'Cooperados',                                    secao:'Domingo Manhã' },
  { id:'fn63', hora:'06:30', texto:'Rotina Diária Cotação Online',                                 caminho:'Serviço Batch/Fornecedores/Rotina Diária Cotação Online',                                   obs:'Fornecedores - Após BI DM',                     secao:'Domingo Manhã' },
  { id:'fn64', hora:'07:00', texto:'Rotina Diária RH (manhã)',                                     caminho:'Serviço Batch/Recursos Humanos/Rotina Diária (manhã)',                                      obs:'Recursos Humanos',                              secao:'Domingo Manhã' },
  { id:'fn65', hora:'07:00', texto:'Job Pgto Diário Automático',                                   caminho:'Serviço Batch/Transporte/Job Pgto Diário Automático',                                       obs:'Transporte',                                    secao:'Domingo Manhã' },
  { id:'fn66', hora:'08:00', texto:'Job Diário Transporte',                                        caminho:'Serviço Batch/Transporte/Job Diário Transporte',                                            obs:'Transporte',                                    secao:'Domingo Manhã' },
  { id:'fn67', hora:'12:00', texto:'Job-APSs Diário - Moinho',                                     caminho:'Serviço Batch/Industrial/Job-APSs Diário - Moinho',                                        obs:'Industrial',                                    secao:'Domingo Manhã' },
  { id:'fn68', hora:'12:00', texto:'Job-APSs Diário - Ração',                                      caminho:'Serviço Batch/Industrial/Job-APSs Diário - Ração',                                         obs:'Industrial',                                    secao:'Domingo Manhã' },
  { id:'fn69', hora:'12:30', texto:'Rotina Diária – AVV e Coamo Brasil',                           caminho:'Serviço Batch/Financeiro/Rotina Diária – AVV e Coamo Brasil',                              obs:'Financeiro',                                    secao:'Domingo Manhã' },

  // ════════════ CORVU DOMINGO ════════════
  { id:'fn70', hora:'—',     texto:'Indústria - MSS após 07:30h',                                  caminho:'Corvu/Indústria - MSS após 07:30h',                                                         obs:'Corvu',                                         secao:'Corvu Domingo' },
  { id:'fn71', hora:'—',     texto:'Bens de Fornecimento - MSS',                                   caminho:'Corvu/Bens de Fornecimento - MSS',                                                          obs:'Corvu',                                         secao:'Corvu Domingo' },
  { id:'fn72', hora:'—',     texto:'Semanal – Outros - MSS',                                       caminho:'Corvu/Semanal – Outros - MSS',                                                              obs:'Corvu',                                         secao:'Corvu Domingo' },

  // ════════════ CARGA BI DOMINGO ════════════
  { id:'fn73', hora:'03:00', texto:'Carga Diária BI_COAMO - STG',                                  caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - STG',                                             obs:'Acompanhamento',                                secao:'Domingo Madrugada' },
  { id:'fn74', hora:'03:00', texto:'Carga Diária BI_COAMO - DW',                                   caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - DW',                                              obs:'Acompanhamento',                                secao:'Domingo Madrugada' },
  { id:'fn75', hora:'03:00', texto:'Carga Diária BI_COAMO - DM',                                   caminho:'Serviço Batch/BI/Carga Diária BI_COAMO - DM',                                              obs:'Acompanhamento',                                secao:'Domingo Madrugada' },

  // ════════════ DOMINGO NOITE — Resetar ════════════
  { id:'fn76', hora:'23:00', texto:'Resetar Servidores',                                           caminho:'Serviço Batch/Resetar Servidores',                                                          obs:'Domingo - Noite',                               secao:'Domingo Noite' },
  { id:'fn77', hora:'23:00', texto:'Servidores de Licença',                                        caminho:'Serviço Batch/Servidores de Licença',                                                       obs:'Domingo - Noite',                               secao:'Domingo Noite' },
  { id:'fn78', hora:'—',     texto:'Lista de funcionários ativos – marcar no job ARHJ001 – ARHR135', caminho:'Serviço Batch/Lista de funcionários ativos – ARHJ001 – ARHR135',                        obs:'Eventual',                                      secao:'Domingo Noite' },
];
